-- IF COL_LENGTH('tableName', 'columnName') IS NOT NULL
IF NOT EXISTS (SELECT *FROM INFORMATION_SCHEMA.TABLES  WHERE TABLE_NAME = 'OBJECT_METADATA')
  BEGIN
      EXECUTE ('CREATE TABLE OBJECT_METADATA
      ( OBJECT_UID INT IDENTITY,
        OBJECT_TYPE VARCHAR(10),
        OBJECT_NAME VARCHAR(30) PRIMARY KEY)')
  END

IF NOT EXISTS (SELECT *FROM OBJECT_METADATA  WHERE OBJECT_NAME = 'USERS' AND OBJECT_TYPE='TABLE')
  BEGIN
      EXECUTE ('CREATE TABLE USERS
      ( USER_UID INT IDENTITY,
        USER_ID VARCHAR(30) PRIMARY KEY,
        USER_FIRST_NAME VARCHAR(30) NOT NULL,
        USER_LAST_NAME VARCHAR(30),
        LANGUAGE_PREFERENCE VARCHAR(30) NOT NULL,
        USER_TYPE VARCHAR(30) NOT NULL,
        ENABLED BIT NOT NULL,
        PASSWORD VARCHAR(30) NOT NULL
        )')        
  END  
IF NOT EXISTS (SELECT *FROM OBJECT_METADATA  WHERE OBJECT_NAME = 'USERS' AND OBJECT_TYPE='TABLE')
  BEGIN
    EXECUTE('INSERT INTO OBJECT_METADATA (OBJECT_TYPE,OBJECT_NAME) VALUES(''TABLE'',''USERS'')')
END

IF NOT EXISTS (SELECT *FROM USERS  WHERE USER_ID = 'Administrator')
  BEGIN
    EXECUTE('INSERT INTO USERS (USER_ID,USER_FIRST_NAME,USER_LAST_NAME,LANGUAGE_PREFERENCE,USER_TYPE,ENABLED,PASSWORD) VALUES(''Administrator'',''Chanky'',''Mallick'',''English'',''ADMIN'',1,''520759'')')
END

IF NOT EXISTS (SELECT *FROM OBJECT_METADATA  WHERE OBJECT_NAME = 'PERMISSIONS' AND OBJECT_TYPE='TABLE')
  BEGIN
      EXECUTE ('CREATE TABLE PERMISSIONS
      ( PERMISSION_UID INT IDENTITY,
        PERMISSION_KEY VARCHAR(30) PRIMARY KEY,
        PERMISSION_NAME VARCHAR(15),
        PERMISSION_DESCRIPTION VARCHAR(MAX)    
        )')        
  END  
IF NOT EXISTS (SELECT *FROM OBJECT_METADATA  WHERE OBJECT_NAME = 'PERMISSIONS' AND OBJECT_TYPE='TABLE')
  BEGIN
    EXECUTE('INSERT INTO OBJECT_METADATA (OBJECT_TYPE,OBJECT_NAME) VALUES(''TABLE'',''PERMISSIONS'')')
END
-- Permission List --
BEGIN
    INSERT INTO PERMISSIONS (PERMISSION_KEY,PERMISSION_NAME,PERMISSION_DESCRIPTION) VALUES ('com.ordermanager.users','')